import './storyInput';
import './storyButton';
import './storyCheck';
import './storySelect';
import './storyLoading';
import './storyText';
import './storyAutocomplete';
import './storyMult';
import './storyRich';
